% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2018 02:14:12
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

trainedModel1 = saveVarsMat.trainedModel1; % <1x1 struct> unsupported class at trainedModel1.predictFcn

clear saveVarsMat;
