% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2018 02:00:02
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('modelo.mat');

trainedModel = saveVarsMat.trainedModel; % <1x1 struct> unsupported class at trainedModel.predictFcn

clear saveVarsMat;
