%para predicciones rapidas, se debe utilizar el YFIT%
%EJEMPLO de ello, primer caso (predicción del Decay de la GT):
clc
clear all
%%
% *BOLD TEXT*
load('DataSet para trabajar Paper.mat')
yfit = trainedModelGaussianProcessCompressorDecay.predictFcn(InputData_Prediction)
%con ello se obtiene la respuesta
%se deben ingresar los 16 valores en el input data para que el sistema
%entregue una respuesta%
%para este caso, se comprueba que en base al análisis de los datos
%modelados en regression learner, la regresión lineal era la que podeía
%menos error y mayor r2%

%para predicciones rapidas, se debe utilizar el YFIT%
%EJEMPLO de ello, primer caso (predicción del Decay de la GT):
clc
clear all
load('DataSet para trabajar Paper.mat')
yfit = trainedModelGaussianProcessCompressorDecay.predictFcn(InputData_Prediction)
%con ello se obtiene la respuesta
%se deben ingresar los 16 valores en el input data para que el sistema
%entregue una respuesta%
%para este caso, se comprueba que en base al análisis de los datos
%modelados en un proceso gausiano, la regresión lineal era la que podeía
%menos error y mayor r2%




function [trainedModel, validationRMSE] = trainRegressionModel(trainedModelLinearRegressionGTDecay)
% [trainedModel, validationRMSE] = trainRegressionModel(trainedModelLinearRegressionGTDecay)
% returns a trained regression model and its RMSE. This code recreates the
% model trained in Regression Learner app. Use the generated code to
% automate training the same model with new data, or to learn how to
% programmatically train models.
%
%  Input:
%      trainingData: a table containing the same predictor and response
%       columns as imported into the app.
%
%  Output:
%      trainedModel: a struct containing the trained regression model. The
%       struct contains various fields with information about the trained
%       model.
%
%      trainedModel.predictFcn: a function to make predictions on new data.
%
%      validationRMSE: a double containing the RMSE. In the app, the
%       History list displays the RMSE for each model.
%
% Use the code to train the model with new data. To retrain your model,
% call the function from the command line with your original data or new
% data as the input argument trainingData.
%
% For example, to retrain a regression model trained with the original data
% set T, enter:
%   [trainedModel, validationRMSE] = trainRegressionModel(T)
%
% To make predictions with the returned 'trainedModel' on new data T2, use
%   yfit = trainedModel.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedModel.HowToPredict

% Auto-generated by MATLAB on 13-Apr-2018 15:54:56


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainedModelLinearRegressionGTDecay;
predictorNames = {'LeverPosition_lp_', 'ShipSpeed_v__knots_', 'GTShaftTorque_GTT__kNM_', 'GTRateOfRevolutions_GTn__rpm_', 'GasGeneratorRateOfRevolutions_GGn__rpm_', 'STBDPropellerTorque_Ts__kN_', 'PRTPropellerTorque_Tp__kN_', 'HPTurbineExitTemperature_T48__C_', 'GTCompressorInletAirTemp_T1__C_', 'GTCompressorOutletAirTemp_T2__C_', 'HPTurbineExitPressure_P48__bar_', 'GTCompressorInletAirPressure_P1__bar_', 'GTCompressorOutletAirPressure_P2__bar_', 'GasTurbineExhaustGasPressure_Pexh__bar_', 'TurbineInjectonControl_TIC____', 'FuelFlow_mf__kg_s_'};
predictors = inputTable(:, predictorNames);
response = inputTable.GTTurbineDecayStateCoefficient_;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a regression model
% This code specifies all the model options and trains the model.
concatenatedPredictorsAndResponse = predictors;
concatenatedPredictorsAndResponse.GTTurbineDecayStateCoefficient_ = response;
linearModel = fitlm(...
    concatenatedPredictorsAndResponse, ...
    'linear', ...
    'RobustOpts', 'off');

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
linearModelPredictFcn = @(x) predict(linearModel, x);
trainedModel.predictFcn = @(x) linearModelPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedModel.RequiredVariables = {'LeverPosition_lp_', 'ShipSpeed_v__knots_', 'GTShaftTorque_GTT__kNM_', 'GTRateOfRevolutions_GTn__rpm_', 'GasGeneratorRateOfRevolutions_GGn__rpm_', 'STBDPropellerTorque_Ts__kN_', 'PRTPropellerTorque_Tp__kN_', 'HPTurbineExitTemperature_T48__C_', 'GTCompressorInletAirTemp_T1__C_', 'GTCompressorOutletAirTemp_T2__C_', 'HPTurbineExitPressure_P48__bar_', 'GTCompressorInletAirPressure_P1__bar_', 'GTCompressorOutletAirPressure_P2__bar_', 'GasTurbineExhaustGasPressure_Pexh__bar_', 'TurbineInjectonControl_TIC____', 'FuelFlow_mf__kg_s_'};
trainedModel.LinearModel = linearModel;
trainedModel.About = 'This struct is a trained model exported from Regression Learner R2018a.';
trainedModel.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appregression_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainedModelLinearRegressionGTDecay;
predictorNames = {'LeverPosition_lp_', 'ShipSpeed_v__knots_', 'GTShaftTorque_GTT__kNM_', 'GTRateOfRevolutions_GTn__rpm_', 'GasGeneratorRateOfRevolutions_GGn__rpm_', 'STBDPropellerTorque_Ts__kN_', 'PRTPropellerTorque_Tp__kN_', 'HPTurbineExitTemperature_T48__C_', 'GTCompressorInletAirTemp_T1__C_', 'GTCompressorOutletAirTemp_T2__C_', 'HPTurbineExitPressure_P48__bar_', 'GTCompressorInletAirPressure_P1__bar_', 'GTCompressorOutletAirPressure_P2__bar_', 'GasTurbineExhaustGasPressure_Pexh__bar_', 'TurbineInjectonControl_TIC____', 'FuelFlow_mf__kg_s_'};
predictors = inputTable(:, predictorNames);
response = inputTable.GTTurbineDecayStateCoefficient_;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Set up holdout validation
cvp = cvpartition(size(response, 1), 'Holdout', 0.2);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a regression model
% This code specifies all the model options and trains the model.
concatenatedPredictorsAndResponse = trainingPredictors;
concatenatedPredictorsAndResponse.GTTurbineDecayStateCoefficient_ = trainingResponse;
linearModel = fitlm(...
    concatenatedPredictorsAndResponse, ...
    'linear', ...
    'RobustOpts', 'off');

% Create the result struct with predict function
linearModelPredictFcn = @(x) predict(linearModel, x);
validationPredictFcn = @(x) linearModelPredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
validationPredictions = validationPredictFcn(validationPredictors);

% Compute validation RMSE
isNotMissing = ~isnan(validationPredictions) & ~isnan(validationResponse);
validationRMSE = sqrt(nansum(( validationPredictions - validationResponse ).^2) / numel(validationResponse(isNotMissing) ));
